rsksmart/liquidity-provider-server

.gitignore
connectors/bitcoin.go
connectors/rsk.go
http/testmocks/rsk_mock.go
main.go
sample-config.json

- added check if a bitcoind node is connected on server start
- allowed gas price to be zero [here](https://github.com/rsksmart/liquidity-provider-server/pull/35/files#diff-4ab681cca396d706fb5744645ffd3c8a5b62661e6906797fb7236136fc451fc9R246)

Added bitcoind connection check

---

go.mod
go.sum
http/server.go
http/server_test.go
http/testmocks/db_mock.go
http/watcher.go
main.go
storage/db.go
storage/queries.go
storage/tables.go

This preserves accepted quotes in db (instead of keeping them in mem)

Added retention of accepted quotes in db

---

.gitignore
connectors/rsk.go
docker-compose/.env
docker-compose/bitcoind/Dockerfile
docker-compose/docker-compose.yml
docker-compose/lbc-deployer/Dockerfile
docker-compose/lbc-deployer/deploy.sh
docker-compose/lps/Dockerfile
docker-compose/lps/config.json
docker-compose/lps/start.sh
docker-compose/rskj/Dockerfile
storage/db.go

Docker-compose for services involved in flyover

Added docker compose

---

connectors/rsk.go

RSK does not support KeepAlives, and LPS was assuming that it does - that's why LPS was having issues with communication with RSK (occasionally RSK<->LPS HTTP connections were being dropped). This change disables preserving http connections with an RSK node for next json-rpc calls.

Fixed RSK connectivity issue by disabling KeepAlives

---

http/server.go
http/server_test.go
postman/LIQUIDITY-PROVIDER-SERVER.postman_collection.json

- Accept quote implementation (It was not taken into account security validations, all business rules should be defined);
- It was accepted LIQUIDITY PROVIDER SERVER postman collection.

Accept quote

---

README.md
http/server.go

Was added a new parameter to the getQuote method.
lpAddress -> The address of the liquidity provider that will do the cross chain conversion

Added new parameter

---

.gitignore
http/server.go

https://rsklabs.atlassian.net/browse/GBI-1083?atlOrigin=eyJpIjoiNmQyZDg1OGVjYTJmNDk3NWIxNTZlNjJlMGNmNWRiMjAiLCJwIjoiaiJ9
https://rsklabs.atlassian.net/browse/GBI-1084?atlOrigin=eyJpIjoiNWI1ZjZjOWJkODZkNDU5ZjhiOTY1MzViODY4NGY4YjkiLCJwIjoiaiJ9
Done ticket 1083 and 1084 together on same validator

[GBI-1083] - Value to transfer not empty

---

http/server.go

[fix] - duplicated code in sonar

---

connectors/bitcoin.go
connectors/rsk.go
http/server.go

https://rsklabs.atlassian.net/browse/GBI-1148?atlOrigin=eyJpIjoiN2JjMzRlNGQ2YmZiNGVlZjlhMjNhMmQ1NWNiNWYxMzIiLCJwIjoiaiJ9
return error for bech32 type while we still dont have implementation

Bitcoin BECH32 Address validation

---

docker-compose/local/rebuild-lps.sh

Create script to rebuild LPS.
It:
- stop and delete LPS container forcefully (without asking)
- delete LPS image
- call .lps-env script to rebuild and run LPS Container/Image
**TODO**: maybe replace with a hot realoding docker file?

Chore - rebuild lps script

---

connectors/bitcoin.go
connectors/bitcoin_test.go

https://rsklabs.atlassian.net/browse/GBI-1165?atlOrigin=eyJpIjoiNTY4NzdkMmE3ZmM5NDBjZWEzY2QyNTI1ODBhOTQyOGUiLCJwIjoiaiJ9

[gbi-1165] - Determine btc address type

---

.github/workflows/e2e.yml

https://rsklabs.atlassian.net/browse/GBI-1172

[GBI-1172] - Fix Healthcheck on E2E Test

---

connectors/bitcoin.go
connectors/rsk.go
go.mod
go.sum
http/server.go

https://rsklabs.atlassian.net/browse/GBI-1150?atlOrigin=eyJpIjoiZGE5MDVjYmIwYTJhNDM3NmI5YTBjZTNkNzE3NTgzOTIiLCJwIjoiaiJ9

[GBI-1150] - Decode bech32 btc address

---

connectors/bindings/lbc.go
docker-compose/local/OpenAPI.yml
http/dto.go
http/server.go

I only added DTOs for pegin because sdk currently doesn't have pegout. With this PR now SDK passes all the integration test with using generated code

Feature/GBI-1187 - Add required fields and DTOs

---

docker-compose/local/OpenAPI.yml
http/dto.go
http/server.go

This PR contains updates on OpenAPI specs comments for Pegout related structures and a little fix on estimate gas parameter on pegout get quote (server.go line 855)

 OpenApi specs and pegout getQuote fix - Feature/GBI-1196

---

internal/adapters/entrypoints/rest/assets/static/configUtils.js
internal/adapters/entrypoints/rest/assets/static/management.js

**What:**
add duplicate confirmation amount check and error
check for negative values in amount fields
implement check for empty confirmation fields
confirmations labeling & added minimum confirmations required
**Tasks:**
[GBI-2291](https://rsklabs.atlassian.net/browse/GBI-2291)
[GBI-2380](https://rsklabs.atlassian.net/browse/GBI-2380)

fix: LP Management-UI | QA-Feedback | GBI-2291 & GBI-2380

---

internal/adapters/entrypoints/rest/assets/static/management.js

**What:**
empty field error labeling
**Task:**
[GBI-2456](https://rsklabs.atlassian.net/browse/GBI-2456)

fix: error labeling | GBI-2456

---

internal/adapters/entrypoints/rest/assets/static/management.js

**What:**
sorts confirmations from lowest rBTC/BTC amount to highest

fix: confirmation sorting | LPS-UI

---

docker-compose/docker-compose.yml
docker-compose/lbc-deployer/Dockerfile
docker-compose/local/docker-compose.lbc-deployer.yml
docker-compose/mainnet/docker-compose.yml
docker-compose/powpeg/pegin/Dockerfile
docker-compose/powpeg/pegout/Dockerfile
docker-compose/rskj/Dockerfile
docker-compose/rskj/rsk.conf

- Update java and rskj version in Dockerfile
- Add rskj service to main docker compose
To be able to update the rskj version in the containers created using the Dockerfile in this project. The next step should be to use the image available in Dockerhub

chore: update rskj version

---

OpenApi.yml
pkg/pegin.go
pkg/pegout.go

Fix typo in creation data DTO and update Open API file accordingly

fix: typo in creation data dto

---

cmd/application/main.go
cmd/utils/key_conversion/key_conversion.go
cmd/utils/refund_user_pegout/refund_user_pegout.go
cmd/utils/register_pegin/register_pegin.go
cmd/utils/scripts/utils.go
cmd/utils/scripts/utils_test.go
cmd/utils/update_provider_url/update_provider_url.go
internal/adapters/entrypoints/rest/assets/static/management.js

- Add `memguard.Purge` in main application
- Add memguard protections to utility scripts
- Set error message using `textContent` property in management UI
Security feedback for v2.1.2 release candidate
https://rsklabs.atlassian.net/browse/GBI-2608
https://rsklabs.atlassian.net/browse/GBI-2605
https://rsklabs.atlassian.net/browse/GBI-2604

v2.1.2 RC - Security feedback

---

.github/workflows/docs.yml

**What:**
Identical copy of approved PR https://github.com/rsksmart/liquidity-provider-server/pull/680 with fixed signing
**Proof:**

feat: DevX Automated Documentation Pipeline | Signed

---

internal/usecases/pegout/get_pegout_report.go
internal/usecases/pegout/get_pegout_report_test.go

UseCase id changed as requested by @Luisfc68.

feat: changed report id name

---

internal/adapters/entrypoints/rest/assets/static/management.js

**What:**
Warning Message once hooked on specific tab doesn't trigger on the opposite tab(pegin/pegout)
**Task:**
[GBI-2648](https://rsklabs.atlassian.net/browse/GBI-2648)

fix: Warning Message once hooked on specific tab doesn't trigger on the opposite tab(pegin/pegout) | GBI-2648

---

internal/adapters/entrypoints/rest/assets/static/configUtils.js
internal/adapters/entrypoints/rest/assets/static/management.js
internal/adapters/entrypoints/rest/common.go
internal/adapters/entrypoints/rest/common_test.go

**What:**
Update warning message
Improve validation error messages
**Tasks:**
[GBI-2643](https://rsklabs.atlassian.net/browse/GBI-2643)
[GBI-2642](https://rsklabs.atlassian.net/browse/GBI-2642)

fix: percentageFee error messages | GBI-2642&GBI-2643

---

internal/adapters/dataproviders/liquidity_provider.go
internal/adapters/dataproviders/liquidity_provider_test.go

- Return 0 instead of negative value if the locked quotes are bigger than the liquidity the liquidity endpoint
- Add `WaitingForDepositConfirmations` to the states considered in the `AvailableLiquidity` function
To improve the UX when using the liquidity endpoints
**Remark:** with this change the client won't be able to tell if there is no liquidity or the change UTXOs are not confirmed yet
https://rsklabs.atlassian.net/browse/GBI-2454

fix: return zero instead of negative values in liquidity endpoint

---

internal/adapters/entrypoints/rest/assets/management.html

add missing data-testid for successToast

add missing data-testid for successToast

---

internal/adapters/entrypoints/rest/assets/management.html
internal/adapters/entrypoints/rest/assets/static/management.css

- Add vertical scrolling on the trusted accounts table.
- Ensure product quality.
[Jira ticket GBI-2843](https://rsklabs.atlassian.net/browse/GBI-2843)
1. Run the LPS on local using `./lps-env.sh up`
2. Follow the description detailed on the Jira tk.
N/A

fix: add vertical scrolling to trusted accounts table
